# Generated by Django 4.2.11 on 2025-10-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_id', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('is_business', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('total_messages', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_message_at'],
                'indexes': [models.Index(fields=['whatsapp_id'], name='contacts_co_whatsap_3b9615_idx'), models.Index(fields=['phone_number'], name='contacts_co_phone_n_6d0af4_idx'), models.Index(fields=['-last_message_at'], name='contacts_co_last_me_b963d7_idx')],
            },
        ),
    ]
